type: 'WBCE_Dice'
weight: 1
start_epoch: 0
kwargs:
  target_str: 'gt_prompted_pred_masks'
  idc: [1]
  alpha_CE: 0.5
  reduction: 'mean'
other_kwargs:
  bounds_name: null
  bounds_params: null
  fn: null
