train_indices : []
num_workers: 16
num_epochs: 20
batch_size: 4
optimizer:
    type: "Adam"
    lr: 0.0001
    weight_decay: 0.0001
sched: 
    update_interval: "epoch"
    update_freq: 1
    MultiStepLR:
        milestones: [10] 
        gamma: 0.1