name: null   # 'comet' for comet_ml, or null (for default tensorboard)
api_key: null   # If name is comet, this is required
workspace: null   # If name is comet, this is required
project_name: null   # If name is comet, this is required
